const ALL_TOOLS = [
  { slug:'merge',        label:'Merge PDF',       description:'Combine multiple PDFs into one document in any order.',                              category:'organize', icon:'merge',        colorFrom:'#f97316', colorTo:'#fb923c', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'split',        label:'Split PDF',       description:'Extract pages or split a PDF into multiple documents.',                            category:'organize', icon:'split',        colorFrom:'#8b5cf6', colorTo:'#a78bfa', acceptedFormats:['.pdf'],                        outputFormat:'zip' },
  { slug:'rotate',       label:'Rotate PDF',      description:'Permanently rotate individual pages or entire PDF documents.',                      category:'organize', icon:'rotate',       colorFrom:'#10b981', colorTo:'#34d399', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'pagenumbers',  label:'Page Numbers',    description:'Add page numbers to your PDF in custom position and style.',                        category:'organize', icon:'pagenumbers',  colorFrom:'#f59e0b', colorTo:'#fbbf24', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'watermark',    label:'Watermark PDF',   description:'Add text or image watermarks to your PDF pages with opacity control.',               category:'edit',     icon:'watermark',    colorFrom:'#ec4899', colorTo:'#f472b6', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'compress',     label:'Compress PDF',    description:'Reduce PDF file size while maintaining quality for easier sharing.',                  category:'optimize', icon:'compress',     colorFrom:'#14b8a6', colorTo:'#2dd4bf', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'pdfa',         label:'PDF to PDF/A',    description:'Convert your PDF to PDF/A format for long-term archival compliance.',               category:'optimize', icon:'pdfa',         colorFrom:'#6366f1', colorTo:'#818cf8', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'pdf-to-word',  label:'PDF to Word',     description:'Convert PDF files into editable Word (DOCX) documents with accurate formatting.',     category:'convert',  icon:'pdf-to-word',  colorFrom:'#2563eb', colorTo:'#60a5fa', acceptedFormats:['.pdf'],                        outputFormat:'docx' },
  { slug:'pdf-to-ppt',   label:'PDF to PPT',      description:'Turn your PDF slides into editable PowerPoint (PPTX) presentations.',                category:'convert',  icon:'pdf-to-ppt',   colorFrom:'#ef4444', colorTo:'#f87171', acceptedFormats:['.pdf'],                        outputFormat:'pptx' },
  { slug:'pdf-to-excel', label:'PDF to Excel',    description:'Extract data from PDF tables into editable Excel (XLSX) spreadsheets.',               category:'convert',  icon:'pdf-to-excel', colorFrom:'#16a34a', colorTo:'#4ade80', acceptedFormats:['.pdf'],                        outputFormat:'xlsx' },
  { slug:'pdf-to-jpg',   label:'PDF to JPG',      description:'Convert each page of your PDF to high-quality JPG images.',                          category:'convert',  icon:'pdf-to-jpg',   colorFrom:'#d97706', colorTo:'#fcd34d', acceptedFormats:['.pdf'],                        outputFormat:'zip' },
  { slug:'html-to-pdf',  label:'HTML to PDF',     description:'Convert HTML pages or code into professional PDF documents.',                         category:'convert',  icon:'html-to-pdf',  colorFrom:'#dc2626', colorTo:'#fb7185', acceptedFormats:['.html'],                       outputFormat:'pdf' },
  { slug:'word-to-pdf',  label:'Word to PDF',     description:'Convert DOC/DOCX files into high-quality PDFs with original formatting preserved.',    category:'convert',  icon:'word-to-pdf',  colorFrom:'#1d4ed8', colorTo:'#93c5fd', acceptedFormats:['.doc','.docx'],                 outputFormat:'pdf' },
  { slug:'ppt-to-pdf',   label:'PPT to PDF',      description:'Convert PowerPoint (PPT/PPTX) presentations into PDF format.',                       category:'convert',  icon:'ppt-to-pdf',   colorFrom:'#b45309', colorTo:'#fbbf24', acceptedFormats:['.ppt','.pptx'],                 outputFormat:'pdf' },
  { slug:'excel-to-pdf', label:'Excel to PDF',    description:'Convert Excel (XLS/XLSX) spreadsheets into PDF documents.',                           category:'convert',  icon:'excel-to-pdf', colorFrom:'#15803d', colorTo:'#86efac', acceptedFormats:['.xls','.xlsx'],                 outputFormat:'pdf' },
  { slug:'jpg-to-pdf',   label:'JPG to PDF',      description:'Convert JPG, JPEG, and PNG images into a single PDF document.',                      category:'convert',  icon:'jpg-to-pdf',   colorFrom:'#7c3aed', colorTo:'#c4b5fd', acceptedFormats:['.jpg','.jpeg','.png'],          outputFormat:'pdf' },
  { slug:'merge-image',  label:'Merge Image',     description:'Merge multiple images together into a single PDF file.',                              category:'convert',  icon:'merge-image',  colorFrom:'#0d9488', colorTo:'#5eead4', acceptedFormats:['.jpg','.jpeg','.png'],          outputFormat:'pdf', isNew:true },
  { slug:'protect',      label:'Protect PDF',     description:'Password-protect your PDF to prevent unauthorized access or editing.',                category:'security', icon:'protect',      colorFrom:'#dc2626', colorTo:'#fca5a5', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'unlock',       label:'Unlock PDF',      description:'Remove password protection from secured PDF documents.',                              category:'security', icon:'unlock',       colorFrom:'#ca8a04', colorTo:'#fde68a', acceptedFormats:['.pdf'],                        outputFormat:'pdf' },
  { slug:'ocr',          label:'OCR PDF',         description:'Extract text from scanned PDFs and images using optical character recognition.',        category:'optimize', icon:'ocr',          colorFrom:'#059669', colorTo:'#6ee7b7', acceptedFormats:['.pdf'],                        outputFormat:'txt' },
];

export default ALL_TOOLS;
